// Share card layout and renderer, v2 (DESIGN 7.1 to 7.4, 8.7, 9.7). Isomorphic: no node:*, no DOM.
//
// renderCard({ ps, size, theme }, hooks?) -> RasterImage
//
// A receipt, not a report: one hero (the archetype name and its line, then the headline value
// drawn large), one signature visual (a 7 x 24 heatmap of when you and your agent work, levels
// only) and four plain-English stats. Landscape (1200 x 675): identity left and value right, then
// the heatmap left and the stats 2 x 2 right, on one two-column grid. Portrait (1080 x 1350): the
// same blocks stacked, stats four across. Free height goes to the headline value first (up to a
// cap) and then evenly to the gaps, so no size, theme or set of hidden stats leaves dead space.
//
// Privacy by construction (traps 47, 48):
// - The only input is a PublicSummary, re-checked with assertPublicSummary before anything is
//   laid out. Nothing else reaches this module.
// - Every string drawn is either fixed copy from CARD_FIXED_COPY or a piece of the manifest
//   text (public.js buildManifest) for one PublicSummary field. layoutCard checks each data
//   piece against its manifest entry and throws if one is not a substring, so the manifest
//   printed next to the card can never under-report what the card shows. The heatmap cells are
//   the PublicSummary heatmap levels, nothing more.
// - Every drawn string goes through hooks.onText before it is drawn (canary test, DESIGN 9.7).
//
// Layout units are logical px (CARD_SIZES); the raster is CARD_SCALE times larger. Text uses
// the pre-rasterized Inter atlas (atlas.js); hero sizes scale an atlas face (drawTextScaled).

import {
  CARD_SIZES, CARD_SCALE, CARD_GRID, CARD_FONT_SIZES, CARD_THEMES, CARD_HEAT, WORDMARK, checkCardOptions,
} from './contract.js';
import { assertPublicSummary, buildManifest, archetypeInfo, badgeText, HEATMAP_TITLE } from '../public.js';
import { getFace, measure64, glyphsFor } from './atlas.js';
import { parseHex, createImage, fillRect, fillRoundRect, drawPill, drawTextScaled } from './raster.js';

/** Brand in the footer (maintainer branding rule: repo URL and elitesystem.ai on the card). */
export const CARD_BRAND = 'elitesystem.ai';

/** Heatmap row labels, Monday first (the PublicSummary row order). */
export const HEAT_DAYS = Object.freeze(['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']);

/** Heatmap hour ticks: [hour column, label]. */
export const HEAT_TICKS = Object.freeze([[0, '12 AM'], [6, '6 AM'], [12, '12 PM'], [18, '6 PM']].map((t) => Object.freeze(t)));

/**
 * Marker drawn on the project's own showcase images ONLY (scripts/make-demo.mjs, README, social
 * posts), never on a card built from someone's real logs. A showcase PNG travels on its own,
 * with no caption attached, so without this the figures on it could be read as real usage. The
 * CLI draws it only for `card --demo-mark`; the default is off and the normal user card is
 * byte-identical to what it was before this marker existed.
 */
export const DEMO_MARK = 'DEMO DATA, NOT REAL USAGE';

/** Every string the card may draw that is not a piece of the manifest text. */
export const CARD_FIXED_COPY = Object.freeze([WORDMARK, CARD_BRAND, DEMO_MARK, ...HEAT_DAYS, ...HEAT_TICKS.map((t) => t[1])]);

/** The four stats, in card order; each is drawn as its manifest text split into number and label. */
export const STAT_FIELDS = Object.freeze(['activeHours', 'toolCalls', 'longestStreakDays', 'delegationShare']);

/** Scale limits: [archetype name max, headline value min, headline value max], per size. */
export const HERO_SCALES = Object.freeze({
  landscape: Object.freeze({ name: 1.3, valueMin: 1.2, valueMax: 2.6 }),
  portrait: Object.freeze({ name: 1.9, valueMin: 1.6, valueMax: 5 }),
});

const FACE_LOGICAL = Object.freeze({
  display: CARD_FONT_SIZES.archetype,
  number: CARD_FONT_SIZES.statNumber,
  line: CARD_FONT_SIZES.archetypeLine,
  label: CARD_FONT_SIZES.statLabel,
  strong: CARD_FONT_SIZES.statLabel,
  footer: CARD_FONT_SIZES.footer,
});

/** Start of the fixed "generated by" sentence of public.js footerText. */
const FOOTER_GENERATED = 'Generated locally by auditrail';

/** Wordmark letter spacing, logical px. */
const WORDMARK_TRACKING = 1.5;

/**
 * @typedef {'text'|'accent'|'secondary'|'ground'} TextRole   ground = the background color (on pills)
 * @typedef {{ kind: 'text', text: string, face: string, scale: number, x: number, y: number, role: TextRole, field: string|null, tracking: number, width: number }} TextOp
 *   x, y: pen origin on the baseline, logical px; width: advance width, logical px
 * @typedef {{ kind: 'pill', x: number, y: number, w: number, h: number }} PillOp   filled with the accent
 * @typedef {{ kind: 'cell', x: number, y: number, w: number, h: number, r: number, level: number }} CellOp
 * @typedef {{ kind: 'rule', x: number, y: number, w: number, h: number }} RuleOp   accent bar
 * @typedef {TextOp|PillOp|CellOp|RuleOp} DrawOp
 * @typedef {{ size: string, width: number, height: number, ops: DrawOp[] }} CardLayout
 */

/* ------------------------------------------------------------------------------------------
 * Text metrics in logical px
 * ---------------------------------------------------------------------------------------- */

/** @param {string} faceId */
function faceOf(faceId) {
  const face = getFace(faceId);
  const want = FACE_LOGICAL[/** @type {keyof typeof FACE_LOGICAL} */ (faceId)] * CARD_SCALE;
  if (face.px !== want) throw new Error('glyph atlas face ' + faceId + ' is ' + face.px + ' px, expected ' + want);
  return face;
}

/**
 * Advance width of a string, logical px, as drawText and drawTextScaled advance the pen.
 * @param {string} faceId
 * @param {string} text
 * @param {number} [tracking] logical px between characters
 * @param {number} [scale]
 */
export function textWidth(faceId, text, tracking = 0, scale = 1) {
  return (measure64(faceOf(faceId), text) * scale + Math.round(tracking * CARD_SCALE * 64) * Math.max(0, text.length - 1)) / 64 / CARD_SCALE;
}

/** @param {string} faceId */
function cap(faceId) { return faceOf(faceId).capHeight / CARD_SCALE; }
/** @param {string} faceId */
function desc(faceId) { return faceOf(faceId).descent / CARD_SCALE; }

/**
 * Ink extent of a string at scale 1, logical px: [above the baseline, below it]. Hero text is
 * spaced by its ink ($ and descenders reach past the cap height and the baseline).
 * @param {string} faceId
 * @param {string} text
 * @returns {[number, number]}
 */
export function inkExtent(faceId, text) {
  let up = 0;
  let down = 0;
  for (const g of glyphsFor(faceOf(faceId), text)) { up = Math.max(up, -g.top); down = Math.max(down, g.top + g.h); }
  return [up / CARD_SCALE, down / CARD_SCALE];
}

/**
 * Line breaking. Segments are preferred break units, kept whole and packed greedily while
 * they fit. A segment wider than the line is broken at spaces; when it fits on two lines the
 * break that makes the longer line shortest is used, otherwise words are packed greedily.
 * A single word wider than the line stays on its own line (the layout tests assert that
 * never happens for real inputs).
 * @param {string} faceId
 * @param {string[]} segments
 * @param {number} maxWidth logical px
 * @returns {string[]}
 */
export function wrapSegments(faceId, segments, maxWidth) {
  const lines = [];
  let cur = '';
  const push = (unit) => {
    const next = cur ? cur + ' ' + unit : unit;
    if (!cur || textWidth(faceId, next) <= maxWidth) cur = next;
    else { lines.push(cur); cur = unit; }
  };
  for (const s of segments) {
    if (textWidth(faceId, s) <= maxWidth) { push(s); continue; }
    const words = s.split(' ').filter(Boolean);
    let best = null;
    for (let k = 1; k < words.length; k++) {
      const a = words.slice(0, k).join(' ');
      const b = words.slice(k).join(' ');
      const wa = textWidth(faceId, a);
      const wb = textWidth(faceId, b);
      if (wa <= maxWidth && wb <= maxWidth && (best === null || Math.max(wa, wb) < best.w)) best = { a, b, w: Math.max(wa, wb) };
    }
    if (best) {
      if (cur) { lines.push(cur); cur = ''; }
      lines.push(best.a);
      cur = best.b;
    } else {
      for (const w of words) push(w);
    }
  }
  if (cur) lines.push(cur);
  return lines;
}

/* ------------------------------------------------------------------------------------------
 * Content: what the card says, from the manifest only
 * ---------------------------------------------------------------------------------------- */

/**
 * The stats in card order, omitting hidden ones: manifest text split at its first space.
 * @param {import('../public.js').PublicSummary} ps
 * @returns {{ field: string, number: string, label: string }[]}
 */
export function statSpecs(ps) {
  const man = new Map(buildManifest(ps).map((e) => [e.field, e.text]));
  return STAT_FIELDS.filter((f) => man.has(f)).map((field) => {
    const t = /** @type {string} */ (man.get(field));
    const i = t.indexOf(' ');
    return { field, number: t.slice(0, i), label: t.slice(i + 1) };
  });
}

/**
 * The headline: the value ("at least", the amount, its label) or, when the value is hidden or
 * not shown, output tokens. Null when both are hidden.
 * @param {Map<string, string>} man
 * @returns {{ field: string, kicker: string|null, number: string, label: string }|null}
 */
function headline(man) {
  const v = man.get('value');
  if (v !== undefined) {
    const rest = v.slice('at least '.length);
    const i = rest.indexOf(' ');
    return { field: 'value', kicker: 'at least', number: rest.slice(0, i), label: rest.slice(i + 1) };
  }
  const o = man.get('outputTokens');
  if (o === undefined) return null;
  const i = o.indexOf(' ');
  return { field: 'outputTokens', kicker: null, number: o.slice(0, i), label: o.slice(i + 1) };
}

/* ------------------------------------------------------------------------------------------
 * Layout
 * ---------------------------------------------------------------------------------------- */

/**
 * Lay the card out without drawing: every text run, pill, heatmap cell and rule with its position.
 * @param {import('../public.js').PublicSummary} ps  must pass assertPublicSummary
 * @param {'landscape'|'portrait'} size
 * @returns {CardLayout}
 */
export function layoutCard(ps, size, opts = {}) {
  assertPublicSummary(ps);
  const demo = opts.demo === true;
  if (!Object.prototype.hasOwnProperty.call(CARD_SIZES, size)) throw new TypeError('size must be landscape or portrait');
  const { width: W, height: H } = CARD_SIZES[size];
  const land = size === 'landscape';
  const M = CARD_GRID.margin;
  const G = CARD_GRID.gutter;
  const CW = W - 2 * M;
  const lim = HERO_SCALES[size];

  /** @type {Map<string, string>} */
  const man = new Map(buildManifest(ps).map((e) => [e.field, e.text]));
  const head = headline(man);
  const stats = statSpecs(ps);

  /** @type {DrawOp[]} */
  const ops = [];
  /**
   * Record one text run after checking where its string comes from.
   * @param {string} str
   * @param {string} face
   * @param {number} x
   * @param {number} y
   * @param {TextRole} role
   * @param {string|null} field  manifest field the string is a piece of; null for fixed copy
   * @param {number} [scale]
   * @param {number} [tracking]
   * @returns {number} advance width
   */
  const text = (str, face, x, y, role, field, scale = 1, tracking = 0) => {
    if (field === null) {
      if (!CARD_FIXED_COPY.includes(str)) throw new Error('card: fixed copy outside CARD_FIXED_COPY');
    } else {
      const src = man.get(field);
      if (src === undefined || !str || !src.includes(str)) throw new Error('card: text for ' + field + ' is not in its manifest entry');
    }
    const width = textWidth(face, str, tracking, scale);
    ops.push({ kind: 'text', text: str, face, scale, x, y, role, field, tracking, width });
    return width;
  };

  // 1. Top bar: wordmark left, coverage right (or under the wordmark when it does not fit), on a
  //    baseline low enough that the tallest ink of either (the | rule) starts on the margin.
  const coverage = man.get('coverage');
  const topBase = M + Math.max(inkExtent('strong', WORDMARK)[0], coverage === undefined ? 0 : inkExtent('label', coverage)[0]);
  const wordmarkW = text(WORDMARK, 'strong', M, topBase, 'accent', null, 1, WORDMARK_TRACKING);
  // Showcase marker, right after the wordmark. It reserves its own width in the coverage fit
  // test below, so turning it on never overlaps the coverage line or moves any other element.
  const markW = demo ? 24 + textWidth('label', DEMO_MARK) : 0;
  if (demo) text(DEMO_MARK, 'label', M + wordmarkW + 24, topBase, 'accent', null);
  let topBottom = topBase + desc('label');
  if (coverage !== undefined) {
    const cw = textWidth('label', coverage);
    if (M + wordmarkW + markW + 24 + cw <= W - M) {
      text(coverage, 'label', W - M - cw, topBase, 'secondary', 'coverage');
    } else {
      const y = topBase + 26;
      text(coverage, 'label', M, y, 'secondary', 'coverage');
      topBottom = y + desc('label');
    }
  }

  // 2. Footer, anchored to the bottom margin, drawn as pieces of the manifest footer text:
  //      value note ................................ scan receipt (right)
  //      Generated locally by auditrail | repo ........ elitesystem.ai (right)
  //    Pieces that do not fit side by side wrap onto their own lines.
  const footerAll = /** @type {string} */ (man.get('footer'));
  const brandW = textWidth('footer', CARD_BRAND);
  const genAt = footerAll.indexOf(FOOTER_GENERATED);
  const scanAt = footerAll.lastIndexOf(' Scanned ');
  /** @type {{ left: string, right: string|null }[]} */
  const rows = [];
  if (genAt > 0 && scanAt > genAt) {
    const note = wrapSegments('footer', footerAll.slice(0, genAt).trim().split(/(?<=\.) /), CW);
    const scan = footerAll.slice(scanAt + 1).trim();
    note.forEach((l) => rows.push({ left: l, right: null }));
    if (textWidth('footer', note[note.length - 1]) + 24 + textWidth('footer', scan) <= CW) rows[rows.length - 1].right = scan;
    else rows.push({ left: scan, right: null });
    wrapSegments('footer', [footerAll.slice(genAt, scanAt).trim()], CW - brandW - 24).forEach((l) => rows.push({ left: l, right: null }));
  } else {
    wrapSegments('footer', [footerAll], CW - brandW - 24).forEach((l) => rows.push({ left: l, right: null }));
  }
  const lead = 22;
  // The last row's ink (the | rule reaches lowest) ends exactly on the bottom margin.
  const lastDown = Math.max(inkExtent('footer', rows[rows.length - 1].left)[1], inkExtent('footer', CARD_BRAND)[1]);
  const firstFooterBase = H - M - lastDown - lead * (rows.length - 1);
  rows.forEach((row, i) => {
    const y = firstFooterBase + lead * i;
    text(row.left, 'footer', M, y, 'secondary', 'footer');
    if (i === rows.length - 1) text(CARD_BRAND, 'footer', W - M - brandW, y, 'text', null);
    else if (row.right !== null) text(row.right, 'footer', W - M - textWidth('footer', row.right), y, 'secondary', 'footer');
  });
  const top = topBottom + (land ? 30 : 56);
  const avail = firstFooterBase - cap('footer') - (land ? 26 : 44) - top;

  // 3. Blocks. Each draws at (x, y) with width w and returns its height; measuring a block is
  //    drawing it at y = 0 and dropping the ops.
  /** @param {() => number} f */
  const measure = (f) => { const n = ops.length; const h = f(); ops.length = n; return h; };

  /** Scale at which a string, with -1 px tracking, is exactly w wide (tracking does not scale). */
  const fitScale = (face, str, w) => (w - textWidth(face, str, -1) + textWidth(face, str)) / textWidth(face, str);
  const nameScale = (w) => (ps.archetype === null ? 1 : Math.min(lim.name, fitScale('display', archetypeInfo(ps.archetype).name, w)));

  /** Identity: archetype name, its line, the badges as filled pills. */
  const identity = (x, y, w) => {
    let b = y;
    if (ps.archetype !== null) {
      const a = archetypeInfo(ps.archetype);
      const s = nameScale(w);
      const [up, down] = inkExtent('display', a.name);
      const nb = y + up * s;
      text(a.name, 'display', x, nb, 'accent', 'archetype', s, -1);
      let lb = nb + Math.max(down * s, 6 * s) + 14 + cap('line');
      for (const line of wrapSegments('line', [a.line], w)) { text(line, 'line', x, lb, 'text', 'archetype'); lb += 34; }
      b = lb - 34 + desc('line');
    }
    if (ps.badges.length) {
      const h = 34;
      let px = x;
      let py = b > y ? b + 20 : y;
      for (const id of ps.badges) {
        const label = badgeText(id, ps).trim();
        const pw = Math.ceil(textWidth('label', label) + 32);
        if (px > x && px + pw > x + w) { px = x; py += h + 10; }
        ops.push({ kind: 'pill', x: px, y: py, w: pw, h });
        text(label, 'label', px + 16, py + (h + cap('label')) / 2, 'ground', 'badges');
        px += pw + 10;
      }
      b = py + h;
    }
    return b - y;
  };

  /** Headline value: kicker, the number at `s` times the stat size, its label. */
  const value = (x, y, w, s) => {
    if (!head) return 0;
    let b = y;
    if (head.kicker) { text(head.kicker, 'line', x, y + cap('line'), 'secondary', head.field); b += cap('line') + desc('line') + 6; }
    const [up, down] = inkExtent('number', head.number);
    const nb = b + up * s;
    text(head.number, 'number', x, nb, 'accent', head.field, s, -1);
    let lb = nb + down * s + 8 + 3 * s + cap('line');
    for (const line of wrapSegments('line', [head.label], w)) { text(line, 'line', x, lb, 'text', head.field); lb += 34; }
    return lb - 34 + desc('line') - y;
  };
  /** Largest value scale whose number fits the width. */
  const valueWidthScale = (w) => (head ? fitScale('number', head.number, w) : lim.valueMax);

  /** Heatmap: title and busiest hour, 7 x 24 cells, day labels, hour ticks. */
  const heat = (x, y, w, maxPitch) => {
    const peak = man.get('peakHourLocal');
    if (ps.heatmap === null && peak === undefined) return 0;
    const dayW = Math.ceil(Math.max(...HEAT_DAYS.map((d) => textWidth('footer', d)))) + 12;
    const pitch = Math.min(maxPitch, (w - dayW) / 24);
    const gap = Math.max(2, Math.round(pitch * 0.16));
    const gx = x + dayW;
    const right = ps.heatmap === null ? x + w : gx + 24 * pitch - gap;
    const hb = y + cap('label');
    if (ps.heatmap !== null) text(HEATMAP_TITLE, 'label', x, hb, 'text', 'heatmap');
    if (peak !== undefined) text(peak, 'label', ps.heatmap === null ? x : right - textWidth('label', peak), hb, 'accent', 'peakHourLocal');
    if (ps.heatmap === null) return hb + desc('label') - y;
    const gy = hb + desc('label') + 16;
    const cell = pitch - gap;
    for (let r = 0; r < 7; r++) {
      text(HEAT_DAYS[r], 'footer', x, gy + r * pitch + (cell + cap('footer')) / 2, 'secondary', null);
      for (let c = 0; c < 24; c++) ops.push({ kind: 'cell', x: gx + c * pitch, y: gy + r * pitch, w: cell, h: cell, r: Math.min(4, cell / 4), level: ps.heatmap[r][c] });
    }
    const tb = gy + 7 * pitch - gap + 12 + cap('footer');
    for (const [h, t] of HEAT_TICKS) text(t, 'footer', gx + h * pitch, tb, 'secondary', null);
    return tb + desc('footer') - y;
  };

  /** Stats: accent rule, number, label lines; `cols` across. */
  const statGrid = (x, y, w, cols) => {
    if (!stats.length) return 0;
    const n = Math.min(cols, stats.length);
    const colW = (w - (n - 1) * G) / n;
    const labels = stats.map((s) => wrapSegments('label', [s.label], colW));
    let b = y;
    for (let r = 0; r * n < stats.length; r++) {
      const idx = stats.map((_, i) => i).filter((i) => Math.floor(i / n) === r);
      const lines = Math.max(...idx.map((i) => labels[i].length));
      const rt = r ? b + 26 : y;
      const nb = rt + 14 + cap('number');
      for (const i of idx) {
        const cx = x + (i % n) * (colW + G);
        ops.push({ kind: 'rule', x: cx, y: rt, w: 28, h: 3 });
        text(stats[i].number, 'number', cx, nb, 'text', stats[i].field);
        labels[i].forEach((l, k) => text(l, 'label', cx, nb + 12 + cap('label') + 22 * k, 'secondary', stats[i].field));
      }
      b = nb + 12 + cap('label') + 22 * (lines - 1) + desc('label');
    }
    return b - y;
  };

  // 4. Composition. The headline scale is solved from the free height (every block height is
  //    linear in it), clamped by its limits and by the width; leftover height is split evenly
  //    between the gaps.
  const hasIdentity = ps.archetype !== null || ps.badges.length > 0;
  const hasLower = ps.heatmap !== null || man.has('peakHourLocal');
  const vh0 = measure(() => value(0, 0, CW, 0));
  const vh1 = measure(() => value(0, 0, CW, 1)) - vh0;
  const fit = (want, w) => Math.max(lim.valueMin, Math.min(lim.valueMax, valueWidthScale(w), want));

  if (land) {
    // Two columns: left wide enough for the heatmap, right for the value and a 2 x 2 of stats.
    const wL = 616;
    const xR = M + wL + 48;
    const wR = W - M - xR;
    const upper = [hasIdentity && 'identity', head && 'value'].filter(Boolean);
    const lower = [hasLower && 'heat', stats.length && 'stats'].filter(Boolean);
    const split = (list, i) => (list.length === 2 ? (i ? [xR, wR] : [M, wL]) : [M, CW]);
    const place = (name, x, y, w, s) => (name === 'identity' ? identity(x, y, w) : name === 'value' ? value(x, y, w, s) : name === 'heat' ? heat(x, y, w, lower.length === 2 ? 30 : 26) : statGrid(x, y, w, lower.length === 2 ? 2 : 4));
    const lowerH = Math.max(0, ...lower.map((n, i) => { const [x, w] = split(lower, i); return measure(() => place(n, x, 0, w, 1)); }));
    const idH = hasIdentity ? measure(() => identity(0, 0, split(upper, 0)[1])) : 0;
    const gapBase = upper.length && lower.length ? 40 : 0;
    const vW = split(upper, upper.indexOf('value'))[1];
    const s = fit((avail - lowerH - gapBase - vh0) / vh1, vW);
    const upperH = Math.max(idH, head ? vh0 + vh1 * s : 0);
    const slack = Math.max(0, avail - upperH - lowerH - gapBase);
    const gaps = upper.length && lower.length ? 3 : 2;
    let y = top + slack / gaps;
    upper.forEach((n, i) => { const [x, w] = split(upper, i); place(n, x, y, w, s); });
    y += upperH + (upper.length ? gapBase + slack / gaps : 0);
    lower.forEach((n, i) => { const [x, w] = split(lower, i); place(n, x, y, w, s); });
  } else {
    // Portrait: stacked, full width.
    const blocks = [hasIdentity && 'identity', head && 'value', hasLower && 'heat', stats.length && 'stats'].filter(Boolean);
    const place = (name, y, s) => (name === 'identity' ? identity(M, y, CW) : name === 'value' ? value(M, y, CW, s) : name === 'heat' ? heat(M, y, CW, 40) : statGrid(M, y, CW, 4));
    const fixedH = blocks.filter((n) => n !== 'value').reduce((a, n) => a + measure(() => place(n, 0, 1)), 0);
    const gapBase = 48 * Math.max(0, blocks.length - 1);
    const s = fit((avail - fixedH - gapBase - vh0) / vh1, CW);
    const used = fixedH + gapBase + (head ? vh0 + vh1 * s : 0);
    const slack = Math.max(0, avail - used) / (blocks.length + 1);
    let y = top + slack;
    for (const n of blocks) y += place(n, y, s) + 48 + slack;
  }
  return { size, width: W, height: H, ops };
}

/* ------------------------------------------------------------------------------------------
 * Render
 * ---------------------------------------------------------------------------------------- */

/**
 * @typedef {Object} TextInfo
 * @property {number} x        pen origin, image px
 * @property {number} y        baseline, image px
 * @property {number} sizePx   em size as drawn, image px (atlas size times the op scale)
 * @property {TextRole} role
 * @property {string|null} field  manifest field the string belongs to; null for fixed copy
 * @property {string} face     atlas face id
 */

/**
 * Render the share card.
 * @param {import('./contract.js').CardInput} input
 * @param {{ onText?: (text: string, info: TextInfo) => void }} [hooks]
 *   onText is called once for every string, before it is drawn
 * @returns {import('./contract.js').RasterImage}
 */
export function renderCard(input, hooks = {}) {
  const problems = checkCardOptions(input);
  if (problems.length) throw new TypeError('card: ' + problems.join('; '));
  const { ps, size, theme } = input;
  assertPublicSummary(ps);
  const layout = layoutCard(ps, size, { demo: input.demo === true });
  const palette = CARD_THEMES[theme];
  /** @type {Record<string, [number, number, number]>} */
  const colors = {
    text: parseHex(palette.text),
    accent: parseHex(palette.accent),
    secondary: parseHex(palette.secondary),
    ground: parseHex(palette.background),
  };
  const heatColors = CARD_HEAT[theme].map(parseHex);
  const S = CARD_SCALE;
  const px = (v) => Math.round(v * S);
  const img = createImage(layout.width * S, layout.height * S, colors.ground);
  for (const op of layout.ops) {
    if (op.kind === 'cell') {
      fillRoundRect(img, px(op.x), px(op.y), px(op.x + op.w) - px(op.x), px(op.y + op.h) - px(op.y), op.r * S, heatColors[op.level]);
    } else if (op.kind === 'pill') {
      drawPill(img, px(op.x), px(op.y), px(op.w), px(op.h), colors.accent);
    } else if (op.kind === 'rule') {
      fillRect(img, px(op.x), px(op.y), px(op.w), px(op.h), colors.accent);
    } else {
      const face = getFace(op.face);
      const x = op.x * S;
      const y = Math.round(op.y * S);
      if (hooks.onText) hooks.onText(op.text, { x, y, sizePx: face.px * op.scale, role: op.role, field: op.field, face: op.face });
      drawTextScaled(img, face, op.text, x, y, colors[op.role], op.scale, Math.round(op.tracking * S * 64));
    }
  }
  return img;
}
