#!/usr/bin/env node
// Builds the live demo page: docs/index.html (DESIGN 10.4).
//
// The page is the normal report file with the SYNTHETIC showcase persona embedded, so a visitor
// sees a full report with nothing installed. The ar-demo slot is set to true, which turns on the
// permanent "synthetic data" banner in the page (src/web/app.js DEMO_BANNER).
//
// It also regenerates the showcase card images used in the README and in any social post. Those
// are rendered with --demo-mark, so the words "DEMO DATA, NOT REAL USAGE" are drawn INTO the
// image: a PNG travels without its caption, and nothing else on it says the figures are fake.
// A card written by a normal `auditrail card` run never carries the marker.
//
// Inputs:  dist/auditrail.mjs (built by scripts/build.mjs)
//          test/fixtures/showcase/power-user/projects (generated by scripts/gen-synthetic.mjs)
// Output:  docs/index.html, docs/.nojekyll, docs/media/auditrail-card{,-portrait}.png
//
// No network, no dependencies. Run: node scripts/make-demo.mjs [--check]

import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { createHash } from 'node:crypto';
import { buildCsp, escapeHtml, inlineScriptHashes } from '../src/node/report.js';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const BUNDLE = path.join(ROOT, 'dist', 'auditrail.mjs');
const FIXTURE = path.join(ROOT, 'test', 'fixtures', 'showcase', 'power-user', 'projects');
const DOCS = path.join(ROOT, 'docs');
const OUT = path.join(DOCS, 'index.html');
const MEDIA = path.join(DOCS, 'media');

/** The showcase cards: [file name, size, theme]. Both carry the demo marker. */
const CARDS = [
  ['auditrail-card.png', 'landscape', 'dark'],
  ['auditrail-card-portrait.png', 'portrait', 'dark'],
];

/** PNG magic, so --check knows it is looking at an image and not an error page. */
const PNG_MAGIC = Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]);

/** Patterns that would make the page reach the network when it is opened. */
const NETWORK_CALLS = [
  'fetch(', 'XMLHttpRequest', 'WebSocket', 'EventSource', 'sendBeacon', 'navigator.connection',
];
/**
 * A subresource loaded from somewhere else. Anchors are links, not loads, and neither is
 * <link rel="canonical">: it is metadata for a crawler, and no browser fetches it. Every other
 * remote <link>, a stylesheet, a preload or an icon, still fails here.
 */
const REMOTE_SUBRESOURCE = /(?:\ssrc\s*=\s*["'](?:https?:|\/\/)|<link(?![^>]*rel\s*=\s*["']canonical["'])[^>]*href\s*=\s*["'](?:https?:|\/\/))/i;

/** Where this page is published. The canonical URL and the JSON-LD url both point at it. */
const PAGE_URL = 'https://0xelitesystem.github.io/auditrail/';

/** One sentence for a crawler and for a link preview. Kept in step with the README opening. */
const PAGE_DESCRIPTION = 'The audit trail your coding agents already wrote, priced at list rates and scanned for leaked secrets, entirely on your own machine. Live demo, running on synthetic data.';

/** The JSON-LD SoftwareApplication. Its author is a Person, never an Organization. */
const JSON_LD = {
  '@context': 'https://schema.org',
  '@type': 'SoftwareApplication',
  name: 'Auditrail',
  applicationCategory: 'DeveloperApplication',
  operatingSystem: 'Any (browser)',
  offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' },
  url: PAGE_URL,
  author: { '@type': 'Person', name: '0xelitesystem', url: 'https://elitesystem.ai' },
};

/**
 * The GEO block: a canonical link, Open Graph tags and the JSON-LD above. None of it loads
 * anything, so the page stays one self-contained file that reaches nothing.
 *
 * The JSON-LD sits in a script element typed application/ld+json. That is a DATA BLOCK: the
 * browser never executes it, so the CSP script-src hash list does not cover it, and adding it
 * cannot invalidate the hashes the report writer already computed (inlineScriptHashes in
 * src/node/report.js skips every non-JavaScript type). assertCspIntact below proves that by
 * recomputing the policy, rather than taking it on trust.
 */
const GEO_BLOCK = [
  '<link rel="canonical" href="' + PAGE_URL + '">',
  '<meta property="og:type" content="website">',
  '<meta property="og:title" content="Auditrail">',
  '<meta property="og:description" content="' + PAGE_DESCRIPTION + '">',
  '<meta property="og:url" content="' + PAGE_URL + '">',
  '<script type="application/ld+json">' + JSON.stringify(JSON_LD) + '</' + 'script>',
].join('\n');

/** The strings the published page must carry (BUILD-SOP "GEO"), checked after the block is in. */
const GEO_NEEDLES = [
  '<link rel="canonical" href="' + PAGE_URL + '">',
  'property="og:title"',
  'property="og:description"',
  'property="og:url"',
  '"@type":"SoftwareApplication"',
  '"@type":"Person"',
];

/** @param {string} msg */
function fail(msg) { console.error('make-demo: ' + msg); process.exit(1); }

/**
 * Put the GEO block at the end of the head. Only the PUBLISHED page gets it. A report written on
 * someone's own machine is published nowhere, so a canonical URL and Open Graph tags pointing at
 * this project's site would be a false statement about a private file: that is why this lives
 * here and not in src/web/template.html.
 * @param {string} html
 * @returns {string}
 */
function addGeo(html) {
  if (html.includes('rel="canonical"')) fail('the page already carries a canonical link');
  const at = html.search(/<\/head>/i);
  if (at < 0) fail('the page has no </head> to put the GEO block in');
  return html.slice(0, at) + GEO_BLOCK + '\n' + html.slice(at);
}

/**
 * The CSP in the page must still be exactly the policy its own inline scripts produce. If an edit
 * to the head ever added or changed an EXECUTABLE script, the hash list would no longer match it
 * and the browser would refuse to run the page. Recompute the policy here instead of assuming.
 * @param {string} html
 */
function assertCspIntact(html) {
  const m = /<meta\b[^>]*http-equiv\s*=\s*["']Content-Security-Policy["'][^>]*content\s*=\s*"([^"]*)"/i.exec(html);
  if (!m) fail('the page has no Content-Security-Policy meta');
  const policy = buildCsp(inlineScriptHashes(html));
  if (!/script-src 'sha256-/.test(policy)) fail('the page lost its inline script-src hashes');
  if (m?.[1] !== escapeHtml(policy)) {
    fail('the CSP no longer matches the inline scripts of the page.\n  in page: ' + m?.[1] + '\n  correct: ' + escapeHtml(policy));
  }
}

function main() {
  const check = process.argv.includes('--check');
  if (!fs.existsSync(BUNDLE)) fail('dist/auditrail.mjs is missing. Run: node scripts/build.mjs');
  if (!fs.existsSync(FIXTURE)) fail('showcase fixture is missing. Run: node scripts/gen-synthetic.mjs');

  const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'ar-demo-'));
  const tmpOut = path.join(tmp, 'demo.html');
  const res = spawnSync(process.execPath, [
    BUNDLE, '--dir', FIXTURE, '--out', tmpOut, '--no-open', '--tz', 'UTC',
  ], { encoding: 'utf8' });
  if (res.status !== 0) fail('the scan failed:\n' + (res.stderr || res.stdout || ''));

  let html = fs.readFileSync(tmpOut, 'utf8');
  fs.rmSync(tmp, { recursive: true, force: true });

  // Turn on the demo banner. ar-data already holds the synthetic Summary.
  const slot = '<script type="application/json" id="ar-demo">';
  const at = html.indexOf(slot);
  if (at < 0 || html.indexOf(slot, at + 1) >= 0) fail('expected exactly one ar-demo slot');
  const end = html.indexOf('</script>', at + slot.length);
  html = html.slice(0, at + slot.length) + 'true' + html.slice(end);

  // This file, and only this file, is the page served from 0xelitesystem.github.io.
  html = addGeo(html);

  // Gates. The demo must be one self-contained file that never reaches the network.
  for (const call of NETWORK_CALLS) {
    if (html.includes(call)) fail('the page contains a network call: ' + call);
  }
  const remote = REMOTE_SUBRESOURCE.exec(html);
  if (remote) fail('the page loads a remote subresource: ' + remote[0]);
  const Q = "(?:'|&#39;)";
  if (!new RegExp('connect-src ' + Q + 'none' + Q).test(html)) fail('the page is missing connect-src none');
  if (!new RegExp('default-src ' + Q + 'none' + Q).test(html)) fail('the page is missing default-src none');
  for (const needle of ['id="ar-data"', 'Demo: every number on this page']) {
    if (!html.includes(needle)) fail('the page is missing: ' + needle);
  }
  // The GEO block, checked as plain strings on the finished page, so a later edit that renames or
  // reorders the parts above cannot quietly drop what the published page is required to carry.
  for (const needle of GEO_NEEDLES) {
    if (!html.includes(needle)) fail('the GEO block is missing: ' + needle);
  }
  if (html.includes('"@type":"Organization"')) fail('the JSON-LD author must be a Person, not an Organization');
  assertCspIntact(html);
  // Nothing from a real machine may reach a public file.
  if (/[A-Za-z]:\\Users\\|\/home\/|\/Users\//.test(html)) fail('the page contains a local path');

  const sha = createHash('sha256').update(html).digest('hex');
  if (check) {
    const current = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8') : '';
    // scanTakenAt changes every run, so compare everything except the data block.
    const strip = (s) => s.replace(/(<script type="application\/json" id="ar-data">)[\s\S]*?(<\/script>)/, '$1$2');
    if (strip(current) !== strip(html)) fail('docs/index.html is stale. Run: node scripts/make-demo.mjs');
    // The cards carry the scan time in their footer, so their bytes change every run and cannot
    // be compared. What is checked is that each one exists and is a PNG. That the marker is
    // actually drawn, and only when asked for, is proved by test/core/card.test.js.
    for (const [name] of CARDS) {
      const f = path.join(MEDIA, name);
      if (!fs.existsSync(f)) fail('docs/media/' + name + ' is missing. Run: node scripts/make-demo.mjs');
      const head = Buffer.alloc(8);
      const fd = fs.openSync(f, 'r');
      fs.readSync(fd, head, 0, 8, 0);
      fs.closeSync(fd);
      if (!head.equals(PNG_MAGIC)) fail('docs/media/' + name + ' is not a PNG');
    }
    console.log('docs/index.html is current');
    return;
  }

  fs.mkdirSync(MEDIA, { recursive: true });
  fs.writeFileSync(path.join(DOCS, '.nojekyll'), '');
  fs.writeFileSync(OUT, html);
  console.log('built docs/index.html (' + Buffer.byteLength(html) + ' bytes, sha256 ' + sha + ')');

  for (const [name, size, theme] of CARDS) {
    const file = path.join(MEDIA, name);
    const r = spawnSync(process.execPath, [
      BUNDLE, 'card', '--dir', FIXTURE, '--out', file, '--no-open', '--tz', 'UTC',
      '--size', size, '--theme', theme, '--demo-mark',
    ], { encoding: 'utf8' });
    if (r.status !== 0) fail('the showcase card failed:\n' + (r.stderr || r.stdout || ''));
    console.log('built docs/media/' + name + ' (' + fs.statSync(file).size + ' bytes, ' + size + ', ' + theme + ', demo marker on)');
  }
}

main();
